### ISSUE TITLE
Feature request: pull from Linkedin to place current employment situation.

### ISSUE THREAD

**Issue by Jack-O-Brian** [Ciaxur/Ciaxur#3]
As the title suggests for the profile, use the Linkedin API to automatically update your current employment status. You can also use a shellscript to set a current project as main, so more people can ~~stalk you~~ understand what you're currently doing.

**Comment by Ciaxur** [comment]
I generalized the README, [#98fb42](https://github.com/Ciaxur/Ciaxur/commit/98fb4205f4954b71d303a3a2377f3ea6d58255b3)
